#!/usr/bin/env bash
# this script installs and configures a new nginx server on ubuntu
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html 
service nginx restart
