#!/usr/bin/env bash
# this script installs and configures a new nginx server on ubuntu
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/location/i \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;\n\t}\n' /etc/nginx/sites-available/default
service nginx restart
