#!/usr/bin/env bash
# this script installs and configures a new nginx server on ubuntu
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "24c\        location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "64c\        error_page 404 /404.html;" /etc/nginx/sites-available/default
service nginx restart
