#!/usr/bin/env bash
# this script installs and configures a new nginx server on ubuntu
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
# update the default page to greet the World.
echo "Hello World!" > /var/www/html/index.nginx-debian.html
# update the redirect me page in the default config
if ! grep -q "location /redirect_me" /etc/nginx/sites-available/default; then
	sed -i '/location/i \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default
else
	sed -i '/return 301/c\\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-available/default
fi
# create the 404 file
echo "Ceci n'est pas une page" > /var/www/html/404.html
# add the error page to the default config befor the location string
if ! grep -q "error_page 404 /404.html;" /etc/nginx/sites-available/default; then
	sed -i '/location \/ {/i \\terror_page 404 /404.html;' /etc/nginx/sites-available/default
else
	sed -i '/error_page 404/c\\terror_page 404 /404.html;' /etc/nginx/sites-available/default
fi
# and finally restart the nginx server
service nginx restart
