#!/usr/bin/env bash
# sets up HAProxy server.
# inatall haproxy
apt-get -y install --no-install-recommends software-properties-common
yes | add-apt-repository ppa:vbernat/haproxy-2.0
apt-get -y install haproxy=2.0.\*
# configure haproxy
if grep -q "backend my_backend" /etc/haproxy/haproxy.cfg; then
	head -n 34 /etc/haproxy/haproxy.cfg > temp && mv temp /etc/haproxy/haproxy.cfg
fi	
echo -e "backend my_backend\n\tbalance roundrobin\n\tserver web-01 54.198.80.67\n\tserver web-02 100.26.152.235" >> /etc/haproxy/haproxy.cfg
echo -e "frontend my_frontend\n\tbind *:80\n\tdefault_backend my_backend" >> /etc/haproxy/haproxy.cfg
service haproxy start
service haproxy restart
update-rc.d haproxy defaults
