#!/usr/bin/env bash
# backs up all mysql databases and compresses it using tar.gz archive.
name=$(date +"%e-%m-%Y.tar.gz")
mysqldump -u root -p"$1" --all-databases > backup.sql && tar -czvf "$name" backup.sql;
