#!/usr/bin/env bash
# this Bash script that displays the content of the file /etc/passwd.
while IFS=':' read -r username x userid x home shell; do
    echo "$username:$userid:$home"
done < /etc/passwd
