#!/usr/bin/env bash
# This Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
while IFS=':' read -r username password userid groupid userinfo homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd
