#!/usr/bin/env bash
# This Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
i=0
while [ "$i" -lt 10 ]
do
	if [ "$i" == 8 ]
	then
		echo "Hi"
		i=$((i+1))
	else
		echo "Best School"
		i=$((i+1))
	fi
done

