#!/usr/bin/env bash
# This Script:
# displays bad luck for the 4th loop iteration, displays good luck for the 8th loop iteration, and displays Best School for the other iterations.
i=0
while [ "$i" -lt 10 ]
do
	if [ "$i" == 3 ]
	then
		echo "bad luck"
		i=$((i+1))
	elif [ "$i" == 7 ]
	then
		echo "good luck"
		i=$((i+1))
	else
		echo "Best School"
		i=$((i+1))
	fi
done

