#!/usr/bin/env bash
# change the user of nginx.
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i 's/^listen .*/listen 8080 default_server;/' /etc/nginx/sites-available/default
service nginx restart
